"""updated column

Revision ID: 2eabf40f1dee
Revises: a6f52b40a3e0
Create Date: 2023-07-26 19:24:59.100998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eabf40f1dee'
down_revision = 'a6f52b40a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_productid_key', type_='unique')
        batch_op.drop_column('productid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('product_productid_key', ['productid'])

    # ### end Alembic commands ###
